#!/bin/bash

echo "🎬 DOWNLOAD HAIR EXTENSION VIDEOS for TyaHair"
echo "=============================================="
echo ""
echo "📋 VIDEO REQUIREMENTS:"
echo "- Resolution: 1920x1080 or higher (HD/4K)"
echo "- Duration: 10-30 seconds (will loop)"
echo "- Style: Premium, elegant, TrueKind-inspired"
echo "- Content: Beautiful hair, hair styling, flowing hair"
echo "- Format: MP4 (web-optimized)"
echo "- Size: Under 5MB for web performance"
echo ""
echo "🎯 RECOMMENDED SEARCH TERMS:"
echo "- 'beautiful long hair flowing'"
echo "- 'hair extensions premium'"
echo "- 'luxury hair styling'"
echo "- 'flowing hair slow motion'"
echo "- 'hair care routine elegant'"
echo ""
echo "📸 RECOMMENDED VIDEO SOURCES:"
echo ""
echo "1. PEXELS VIDEOS (Free): https://www.pexels.com/videos/"
echo "   Search: 'hair', 'beautiful hair', 'hair care'"
echo "   - High quality stock videos"
echo "   - Free commercial use"
echo "   - Good selection of hair-related content"
echo ""
echo "2. UNSPLASH (Some videos): https://unsplash.com/"
echo "   Search: 'hair video', 'beauty video'"
echo "   - Premium quality"
echo "   - Free for commercial use"
echo ""
echo "3. PIXABAY VIDEOS: https://pixabay.com/videos/"
echo "   Search: 'hair', 'beauty', 'hair care'"
echo "   - Good free options"
echo "   - Various quality levels"
echo ""
echo "4. FREEPIK (Paid): https://www.freepik.com/videos"
echo "   Search: 'hair extensions', 'premium hair'"
echo "   - High quality premium content"
echo "   - Subscription required"
echo ""
echo "📂 SAVE VIDEOS AS:"
echo "- public/videos/hero-hair-main.mp4     (Primary background)"
echo "- public/videos/hero-hair-alt.mp4      (Alternative/fallback)"
echo ""
echo "🎨 STYLE INSPIRATION:"
echo "- Warm, golden lighting like TrueKind"
echo "- Smooth, flowing movements"
echo "- Natural, organic feel"
echo "- Premium, luxurious aesthetic"
echo ""
echo "💡 SPECIFIC VIDEO IDEAS:"
echo "- Close-up of beautiful long hair being brushed"
echo "- Hair flowing in slow motion with warm lighting"
echo "- Hair extensions being gently touched/styled"
echo "- Hair care routine with premium products"
echo "- Elegant hair styling process"
echo ""
echo "⚡ OPTIMIZATION TIPS:"
echo "- Compress videos after download"
echo "- Test loading speed"
echo "- Ensure smooth looping"
echo "- Add fallback image for slow connections"
echo ""
echo "✅ AFTER DOWNLOADING:"
echo "1. Place videos in public/videos/ folder"
echo "2. Test video loading in browser"
echo "3. Update HeroSection component to use video"
echo "4. Add proper fallback systems"
echo ""
echo "🔗 QUICK LINKS TO START:"
echo "- Pexels Hair Videos: https://www.pexels.com/search/videos/hair/"
echo "- Pixabay Hair Videos: https://pixabay.com/videos/search/hair/"
echo ""
echo "Happy downloading! 🎬✨"